### ISSUE TITLE
iOS的支付宝回调问题

### ISSUE THREAD

**Issue by doudadou** [daihere1993/cordova-plugin-xpay#1]
您好，支付功能可以调通，但是支付后支付宝扣款成功，显示了一个空白页，然后没有回调，请问您知道是哪里的问题吗

**Comment by daihere1993** [comment]
这个bug我刚才改了下代码和Readme，你rm掉当前的xpay然后根据新的Readme重写再add一次应该就没问题了

**Comment by doudadou** [comment]
支付宝可以了回调了成功了，目前用了6、7个只有你这个在ionic3上可以走通的，感谢！
微信还没测，测好了反馈
