### ISSUE TITLE
iOS提交审核会报alipay不允许只使用数字Schemes

### ISSUE THREAD

**Issue by doudadou** [daihere1993/cordova-plugin-xpay#2]
RT

**Comment by daihere1993** [comment]
提交审核？什么意思

**Comment by daihere1993** [comment]
你的xcode是什么版本

**Comment by doudadou** [comment]
就是使用xcode打版本上传app到苹果商店测试的时候，它会检查Schemes的类型，如果只是用数字会报错误提示，不允许提交。
http://www.qingpingshan.com/rjbc/ios/247726.html
Xcode Version 8.3.3 (8E3004b)

**Comment by daihere1993** [comment]
ok，我大概知道了，我待会改一下schmes的初始结构。

**Comment by doudadou** [comment]
好的，感谢

**Comment by daihere1993** [comment]
我提交了，你卸载了重新安装下

**Comment by doudadou** [comment]
好，要晚上回去尝试下

**Comment by doudadou** [comment]
更新了以后，支付宝不回调了。。，我也尝试重新rm掉platform，重新建立过

**Comment by daihere1993** [comment]
对，是我疏忽了。这里有个bug，我已经改了。你再试试，应该可以了~

**Comment by doudadou** [comment]
只能晚上我回去试下了，捎带着说下那个Wechat payment的实例的字段名，应该是驼峰命名（partnerId、prepayId、nonceStr、timeStamp）的，会提示找不到那几个字段报错

**Comment by daihere1993** [comment]
不会报错的，我java代码里面的字段名是驼峰命名

**Comment by doudadou** [comment]
我是说你的 README 的Usage示例Wechat payment部分是小写的

**Comment by daihere1993** [comment]
恩，晚点我去改改。

**Comment by doudadou** [comment]
支付宝可以回调了，感谢
