### ISSUE TITLE
Android微信支付问题

### ISSUE THREAD

**Issue by doudadou** [daihere1993/cordova-plugin-xpay#3]
- Android微信支付成功后没回调app支付页面，而是重新打开了app；

- 想要装https://github.com/xu-li/cordova-plugin-wechat 这个插件，但是和你的插件好像有冲突，装完你和他的其中一个插件，再装另外一个会冲突，build会失败。觉得应该是他的里面也有支付功能的原因。但是我用了他的支付功能没成功。。。，因为后续想加入微信分享、登录功能，所以可以处理下吗？还是我在哪里修改下避免冲突呢？

**Comment by daihere1993** [comment]
1. Android的微信支付我这边测过了，没有出现你说的那个问题。你看看是不是其他的问题。
2. 和其他微信相关的插件一起使用时冲突的原因是两个插件重复引用了相同文件名，这个问题晚点我研究下。

**Comment by doudadou** [comment]
好的，我使用的魅族M4微信支付完重新打开了app。我再重新装下试试看

**Comment by daihere1993** [comment]
不好意思，回復的有點慢了。
我研究了很久，由於微信把所有相關功能的sdk都集成在了一起，所以發現無法和其他的微信插件兼容。
如果你即需支付寶支付還需要微信的其他功能，建議使用[cordova-plugin-x-alipay](https://github.com/daihere1993/cordova-plugin-x-alipay)和[cordova-plugin-wechat](https://github.com/xu-li/cordova-plugin-wechat)。另外我試了下cordova-plugin-wechat提供的支付接口，是有效的。
希望我的回答對你有幫助🙏。
