### ISSUE TITLE
使用xpay插件调用支付宝支付问题

### ISSUE THREAD

**Issue by dsitn201703** [daihere1993/cordova-plugin-xpay#4]
你好，我安装了cordova-plugin-xpay插件，然后在调用支付宝支付时，后端服务已经返回了订单字符串信息，但是app界面上并未跳转到手机支付宝app，并且支付宝返回给我的内容是： memo : "系统繁忙，请稍后再试"     resultStatus：“4000”。请问这是什么原因？另外，我在install 插件时，看见要添加alipay appid这个变量，我使用的是沙箱环境的appid，会是这个原因吗？

**Comment by daihere1993** [comment]
你把後台返回的字符串貼出來看下。

**Comment by dsitn201703** [comment]
alipay_sdk=alipay-sdk-java-dynamicVersionNo&app_id=2016081900286832
&biz_content=%7B%22body%22%3A%22%E6%88%91%E6%98%AF%E6%B5%8B%E8%AF%95%E6%95%B0%E6%8D%AE%22%2C%22
out_trade_no%22%3A%2217092905000002%22%2C%22product_code%22%3A%22QUICK_MSECURITY_PAY%22%2C%22subject
%22%3A%22App%E6%94%AF%E4%BB%98%E6%B5%8B%E8%AF%95Java%22%2C%22timeout_express%22%3A%2290m%22%2C%22
total_amount%22%3A%22amount%22%7D&charset=UTF-8&format=json&method=alipay.trade.app.pay&
notify_url=http%3A%2F%2Ftianna.tunnel.qydev.com%2Fmss-app%2FalipayNotifyResponse&
sign=bLwFWKjWR%2BIsrzQg6MwsRoxsdYsl50xDDOjmI04jAT6VsIrszEL7rWjgXZUtKyXhd1MqrmXpHHiDp5bKo9Xbw0Wpp%2BZ5AN%2BbgllVLhFJ1RScmyESB3XnwByaiHdzvInBQgrTL20K63GThCKvjEYnCz65HUjHAkDZy3kY4xLr1iy2FawqIfwmt7BJtvKDUwc5oop87J1eEIxGVdCFtHCpKNcidbaBU9pm1t1kq8Jwcrl%2BVXghTyI5%2FfkHg9JL8CgifcyARRLw3PIk7YJPnZQCLj0zUJbTk%2BiHIiQ9ArVk7srV%2F6nVz5OhElA3lqrDNYr4j9hKcF8RRrT3Utebpy%2FBoA%3D%3D&
sign_type=RSA2&
timestamp=2017-09-29+13%3A59%3A00&
version=1.0

**Comment by daihere1993** [comment]
1. 你使用的是什麼手機。
2. 你手機有沒有支付寶的APP。

**Comment by dsitn201703** [comment]
1. 手机型号是小米4，操作系统 MIUI8.2.1稳定版
2. 手机里安装的是安卓支付宝app 沙箱板

**Comment by daihere1993** [comment]
提示系統繁忙一般都是簽名不對。
參考：https://openclub.alipay.com/read.php?tid=543&fid=2

**Comment by dsitn201703** [comment]
关于这个签名的问题，我之前也是用的这一套签名，做了一个手机网页支付的功能，这个是可以成功跳转并支付的，现在我就是用cordova打包成了APP， 用的还是之前用过的签名，现在就提示系统繁忙了，而且都没有调起手机上的支付宝app。手机网页支付和手机app支付能不能用同一个沙箱账号的签名？

**Comment by daihere1993** [comment]
網頁支付和APP支付是分開的，不能使用同一個簽名。

**Comment by dsitn201703** [comment]
再次麻烦请教一下这个插件，我重新生成了签名，然后再次测试发现还是会提示"系统繁忙，请稍后再试" ，另外我还是用了支付宝官网提供的一份请求参数直接使用xpay()方法调用，也是会提示相同的错误，我想再次确认一下，您的这个插件可不可以使用沙箱的appid来使用？因为我一直使用的是沙箱账号。

**Comment by daihere1993** [comment]
首先，我這個插件是針對APP支付的，如果你使用的appid不是APP支付的ip，那肯定是不對的。
其次，理論上來說，沙箱的appid應該也是可以用的，但我沒有試過~
我估計你還是那一步驟出錯了吧。
